### PR TITLE
Some minor changes to URLs and Ruby and Rails versions

### PR DESCRIPTION
**Pull request by Manfred**

### CODE REVIEW

**Comment by tvandervossen** [comment]
Isn’t Rails 5 still in beta? IMHO it’s probably still better for beginners to go with 4.2.6 because that’s what most documentation currently available assumes people will be using. Even the official guides are still for 4.2 only.

**Comment by Manfred** [comment]
Yes, 5.0 is in beta.

**Comment by tvandervossen** [comment]
Can you take out the 5.0 thing for now? Everything else looks great to me.

**Comment by Manfred** [comment]
I change the Rails version to the latest stable one instead of the beta version.

**Pull request merged**
